In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.11.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    res = sess.run(hello + world)

In [9]:
print(res)

b'Hello WOrld'


In [10]:
a = tf.constant(10)
b = tf.constant(20)

In [11]:
type(a)

tensorflow.python.framework.ops.Tensor

In [12]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [13]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [14]:
with tf.Session() as sess:
    res = sess.run(a + b)

In [15]:
res

30

In [16]:
const = tf.constant(10)
fill_mat = tf.fill((4, 4), 10)
zeros = tf.zeros((4, 4))
ones = tf.ones((4, 4))
randn = tf.random_normal((4, 4), mean=0, stddev=1.0)
randu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [17]:
ops = [const, fill_mat, zeros, ones, randn, randu]

In [18]:
sess = tf.InteractiveSession()

In [19]:
for op in ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.5882794  -1.5188067  -0.93969774  1.3325611 ]
 [-0.6504114  -0.35815957 -2.1574883  -0.0315752 ]
 [ 1.766921    1.4501367   0.45739657 -0.9829003 ]
 [-1.7608349   0.51274395 -0.04149336 -0.3037842 ]]


[[0.10030925 0.49699926 0.6668428  0.6183722 ]
 [0.17028451 0.02277422 0.5311303  0.3053038 ]
 [0.16456354 0.04080582 0.60090625 0.5700108 ]
 [0.6677072  0.695083   0.5627508  0.8482764 ]]




In [20]:
a = tf.constant([[1, 2], [3, 4]])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [21]:
b = tf.constant([[10], [100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [22]:
res = tf.matmul(a, b)

In [23]:
sess.run(res)

array([[210],
       [430]], dtype=int32)

In [24]:
res.eval()

array([[210],
       [430]], dtype=int32)